services:
  open-webui:
    build:
      args:
        OLLAMA_API_BASE_URL: "/ollama"
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui2
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
